# GoCD Pipeline definitions - see https://github.com/tomzo/gocd-yaml-config-plugin
format_version: 4
environments:
  test:
    environment_variables:
      DEPLOYMENT: testing
    pipelines:
      - action-movies
      - action-movies-manual
  dev:
    environment_variables:
      DEPLOYMENT: testing
    pipelines:
      - animation-movies
      - animation-and-action-movies
      - both
pipelines:
  action-movies:
    group: movies
    secure_variables:
      ARTIFACTORY_NPM_TOKEN_IN_QUOTES: "AES:MTIzNDU2NzhhYmRlcXdlcg==:Q900zW4SwcmIIGLsDKwZBQ=="
      TestPassword: AES:MTIzNDU2NzhhYmRlcXdlcg==:cPNqaJwI7qQb4TE09mCH9eAAAxLJurAMG2R7UQjDOEY=
    materials:
      action:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/TWChennai/gocd-git-path-sample.git
          path: action
          shallow_clone: true
    stages:
      - build:
          jobs:
            build:
              tasks:
                - script: ./run.sh action
              artifacts:
                - build:
                    source: action/movies.txt
                    destination: ''
           
  action-movies-manual:
    group: movies
    materials:
      action-manual:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/TWChennai/gocd-git-path-sample.git
          path: action
    stages:
      - build:
          approval: manual
          jobs:
            build:
              tasks:
                - script: ./run.sh action
  animation-movies:
    group: movies
    materials:
      animation:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/TWChennai/gocd-git-path-sample.git
          path: animation
    stages:
      - build:
          jobs:
            build:
              resources:
               - linux
              tasks:
                - script: ./run.sh animation
  animation-and-action-movies:
    group: movies
    materials:
      animation-and-action:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/TWChennai/gocd-git-path-sample.git
          path: animation, action
          shallow_clone: true
    stages:
      - build:
          jobs:
            build:
              elastic_profile_id: "test-profile"
              tasks:
                - script: ./run.sh animation
                - script: ./run.sh action
  both:
    group: movies
    materials:
      action:
        pipeline: action-movies
        stage: build
      action-movies-manual:
        pipeline: action-movies-manual
        stage: build
      animation:
        pipeline: animation-movies
        stage: build
      animation-and-action-movies:
        pipeline: animation-and-action-movies
        stage: build
      integration:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/TWChennai/gocd-git-path-sample.git
          path: integration
          shallow_clone: true
    stages:
      - build:
          jobs:
            build:
              tasks:
                - script: echo "Run OK"
